

#input_file: /data/share/DATA/PROC/ERA5/ERA5_3hourly_230101-250430.nc
input_file: /data/share/DATA/PROC/ERA5/ERA5_merged_20250531-20250701.nc
output_file: /data/share/DATA/PROC/ERA5_ROMS_F/ROMS_F_ERA5_3hourly_250531-250701.nc
ref_time: days since 2000-1-1 00:00:00


dt: hourly


