# 

# === Download config ===
time:
  start: "2025-06-30"
  end:   "2025-07-01"

region:
  lat: [5, 60]
  lon: [100, 180]

output:
  base_dir: "/home/shjo/data/test/hycom/"

# === Preprocess config ===

# --- Initial & Boundary and Forcing ---
ininame : /data/share/DATA/ROMS_INPUTS/ini/yes2k_ini_230101.nc
bryname : /data/share/DATA/ROMS_INPUTS/bry/roms_bry_npzd_15km_v2_250430_250701.nc
grdname : /data/share/DATA/ROMS_INPUTS/grd/roms_grd_fennel_15km_smooth_v2.nc
frcname: test_grib.nc

weight_file: /data/share/DATA/ROMS_INPUTS/wght/NWP_weight.nc
calc_weight: True

ncformat: NETCDF4 # NETCDF3_64BIT
force_write: True

flood_method_for_ini: griddata #griddata / edt / linearND
flood_method_for_bry: edt      #griddata / edt / linearND
 
initdate            : 2023-01-01 00:00:00 # 'YYYY-MM-DD HH:MM:SS'
ogcm_name_ini       : /data/share/DATA/RAW/00utc/HYCOM_20230101_00UTC.nc 
ogcm_path_bry       : /home/shjo/ROMS/romsforge/py/dev_individual/getdata/test/

ogcm_var_name:
    longitude       : lon
    latitude        : lat
    depth           : depth
    time            : time
    temperature     : water_temp
    salinity        : salinity
    u               : water_u
    v               : water_v
    zeta            : surf_el

bry_start_date      : 2025-04-30 00:00:00 # 'YYYY-MM-DD HH:MM:SS'
bry_end_date        : 2025-07-01 00:00:00 # 'YYYY-MM-DD HH:MM:SS'

time_ref            : seconds since 2000-1-1 00:00:00

global_attrs_ini: 
    title           : ROMS ini
    clm_file        : ROMS ini
    type            : ROMS ini
    history         : history

global_attrs_bry: 
    title           : ROMS bry
    clm_file        : ROMS bry
    type            : ROMS bry
    history         : history

vertical:
    layer_n         : 36
    vtransform      : 2
    vstretching     : 4
    theta_s         : 6.5
    theta_b         : 1
    tcline          : 400

# === Add bio ===
bio_type : None
















