###
#
# INFO
# This script is for HYCOM data
###

# === Define file names ===
ininame : /home/shjo/data/roms_inputs/ini/lte/NWP4_ini_3_10m_LP_subsampled.nc
#ininame : /home/shjo/data/roms_inputs/ini/lte/NWP12_ini_edit.nc
bryname : /home/shjo/data/roms_inputs/bry/lte/NWP12_bry_edit.nc
grdname : /home/shjo/data/roms_inputs/grd/lte/NWP4_grd_3_10m_LP_subsampled.nc
#grdname : /home/shjo/data/roms_inputs/grd/lte/NWP12_grd_edit_depth.nc

weight_file: /home/shjo/data/roms_inputs/wght/wght_hycom_nwp4.nc
calc_weight: False

ncformat: NETCDF4 # NETCDF3_64BIT
force_write: True

bio_model_type: fennel

initdate            : 2023-01-01 00:00:00 # 'YYYY-MM-DD HH:MM:SS'
ogcm_name           : /home/shjo/data/raw/00utc/HYCOM_20230101_00UTC.nc

flood_method_for_ini: griddata #griddata / edt / linearND
flood_method_for_bry: edt #griddata / edt / linearND

ogcm_path: /home/shjo/data/raw/00utc/

ogcm_var_name:
    longitude       : lon
    latitude        : lat
    depth           : depth
    time            : time
    temperature     : water_temp
    salinity        : salinity
    u               : water_u
    v               : water_v
    zeta            : surf_el

bry_start_date      : 2022-12-31 00:00:00 # 'YYYY-MM-DD HH:MM:SS'
bry_end_date        : 2025-01-01 00:00:00 # 'YYYY-MM-DD HH:MM:SS'

time_ref            : seconds since 1980-1-1 00:00:00

global_attrs: 
    title           : ROMS ini
    clm_file        : ROMS ini
    type            : ROMS ini

vertical:
    layer_n         : 20
    vtransform      : 2
    vstretching     : 2
    theta_s         : 7.0
    theta_b         : 0.1
    tcline          : 200




