###
#
# INFO
# This script is for HYCOM data
###

# === Define file names ===
#ininame : /mnt/c/Users/shjo9/Bridge/DATA/roms_ini.nc
#grdname : /mnt/c/Users/shjo9/Bridge/DATA/NWP4_grd_3_10m_LP.nc
bryname : /data/share/DATA/ROMS_INPUTS/bry/test.nc
#bryname : /data/share/DATA/ROMS_INPUTS/bry/test_250531_250603.nc
grdname : /data/share/DATA/ROMS_INPUTS/grd/roms_grd_fennel_15km_smooth_v2.nc

#weight_file: /mnt/c/USers/shjo9/Bridge/DATA/NWP4_weight_10m_LP.nc
weight_file: /data/share/DATA/ROMS_INPUTS/wght/NWP_weight.nc
calc_weight: False

ncformat: NETCDF4 # NETCDF3_64BIT
force_write: True

bio_model_type: npzd

flood_method_for_bry: edt #griddata / edt / linearND

ogcm_path: /data/share/DATA/RAW/00utc/
#ogcm_path: /data/share/DATA/RAW/Bvar/NUT/

ogcm_var_name:
    longitude       : lon
    latitude        : lat
    depth           : depth
    time            : time
    temperature     : water_temp
    salinity        : salinity
    u               : water_u
    v               : water_v
    zeta            : surf_el

bry_start_date      : 2025-04-30 00:00:00 # 'YYYY-MM-DD HH:MM:SS'
bry_end_date        : 2025-05-03 00:00:00 # 'YYYY-MM-DD HH:MM:SS'

time_ref            : seconds since 2000-1-1 00:00:00

global_attrs: 
    title           : ROMS bry
    clm_file        : ROMS bry
    type            : ROMS bry

vertical:
    layer_n         : 36
    vtransform      : 2
    vstretching     : 4
    theta_s         : 6.5
    theta_b         : 1
    tcline          : 400




