###
#
# INFO
# This script is for HYCOM data
###

# === Define file names ===
#ininame : /mnt/c/Users/shjo9/Bridge/DATA/roms_ini.nc
#grdname : /mnt/c/Users/shjo9/Bridge/DATA/NWP4_grd_3_10m_LP.nc
bryname : /data/share/DATA/ROMS_INPUTS/bry/yes2k_bry_241231_230202.nc
#bryname : /data/share/DATA/ROMS_INPUTS/bry/test_250531_250603.nc
grdname : /data/share/DATA/ROMS_INPUTS/grd/yes2k_grd.nc

#weight_file: /mnt/c/USers/shjo9/Bridge/DATA/NWP4_weight_10m_LP.nc
weight_file: /data/share/DATA/ROMS_INPUTS/wght/yes2k_weight.nc
calc_weight: True

ncformat: NETCDF3_64BIT # NETCDF4 # NETCDF3_64BIT
force_write: True

bio_model_type: none

flood_method_for_bry: edt #griddata / edt / linearND

ogcm_path: /data/share/DATA/RAW/00utc/
#ogcm_path: /data/share/DATA/RAW/Bvar/NUT/

ogcm_var_name:
    longitude       : lon
    latitude        : lat
    depth           : depth
    time            : time
    temperature     : water_temp
    salinity        : salinity
    u               : water_u
    v               : water_v
    zeta            : surf_el

bry_start_date      : 2022-12-31 00:00:00 # 'YYYY-MM-DD HH:MM:SS'
bry_end_date        : 2023-02-02 00:00:00 # 'YYYY-MM-DD HH:MM:SS'

time_ref            : seconds since 2000-1-1 00:00:00

global_attrs: 
    title           : ROMS bry
    clm_file        : ROMS bry
    type            : ROMS bry

vertical:
    layer_n         : 30
    vtransform      : 2
    vstretching     : 4
    theta_s         : 7
    theta_b         : 2
    tcline          : 100




