# 

# === Download config ===
time:
  start: "2025-07-31"
  end:   "2025-09-04"

region:
  lat: [5, 60]
  lon: [100, 179]

output:
  base_dir: "/home/shjo/data/nifs02/aug/"

core_num : 3 # currently not working

# === Preprocess config ===

# --- Initial & Boundary and Forcing ---
grdname : /home/shjo/data/roms_inputs/grd/lte/NWP12_grd_NWP4.nc
ininame : ./add_incre_1cycle.nc

weight_file: ./NWP_weight.nc
calc_weight: True

ncformat: NETCDF4 # NETCDF3_64BIT
force_write: True

flood_method_for_ini: griddata #griddata / edt / linearND
flood_method_for_bry: edt      #griddata / edt / linearND
 
initdate            : 2025-08-01 00:00:00 # 'YYYY-MM-DD HH:MM:SS'
ogcm_name           : /data/shjo/mcc/aug/hycom/HYCOM_20250701_00UTC.nc
#ogcm_path_bry      : This will set automaticaly 

bio_model_type      : npzd # None npzd, fennel 

ogcm_var_name:
    longitude       : lon
    latitude        : lat
    depth           : depth
    time            : time
    temperature     : water_temp
    salinity        : salinity
    u               : water_u
    v               : water_v
    zeta            : surf_el

bry_start_date      : 2025-07-31 00:00:00 # 'YYYY-MM-DD HH:MM:SS'
bry_end_date        : 2025-09-04 00:00:00 # 'YYYY-MM-DD HH:MM:SS'

time_ref            : seconds since 2000-1-1 00:00:00

global_attrs: 
    title           : ROMS ini
    clm_file        : ROMS ini
    type            : ROMS ini
    history         : history

global_attrs_bry: 
    title           : ROMS bry
    clm_file        : ROMS bry
    type            : ROMS bry
    history         : history

vertical:
    layer_n         : 20
    vtransform      : 2
    vstretching     : 2
    theta_s         : 7
    theta_b         : 0.1
    tcline          : 200

# === Add bio ===
bio_ogcm_name : /data/share/DATA/RAW/Bvar_hindcast/clm_CMEMS_bio.nc

bio_ogcm_var_name:
    longitude       : longitude
    latitude        : latitude
    depth           : depth
    time            : time
    phyt            : phyc
    NO3             : no3
    PO4             : po4
    oxygen          : o2
    chl             : chl
    














