
# === Preprocess config ===

# --- Initial & Boundary and Forcing ---
grdname_src : /home/shjo/data/roms_inputs/grd/lte/NWP12_grd_NWP4.nc
grdname_dst : /home/shjo/data/roms_inputs/grd/lte/NWP12_grd_NWP4.nc

ininame : ./add_incre_1cycle.nc

weight_file: ./NWP_weight.nc
calc_weight: True

ncformat: NETCDF4 # NETCDF3_64BIT
force_write: True

global_attrs: 
    title           : ROMS ini
    clm_file        : ROMS ini
    type            : ROMS ini
    history         : history

global_attrs_bry: 
    title           : ROMS bry
    clm_file        : ROMS bry
    type            : ROMS bry
    history         : history

vertical_src:
    layer_n         : 20
    vtransform      : 2
    vstretching     : 2
    theta_s         : 7
    theta_b         : 0.1
    tcline          : 200

vertical_dst:
    layer_n         : 36
    vtransform      : 2
    vstretching     : 2
    theta_s         : 7
    theta_b         : 0.1
    tcline          : 200















