###
#
# INFO
# This script is for HYCOM data
###

# === Define file names ===
bryname : /data/share/DATA/ROMS_INPUTS/bry/test_multi_bry.nc
grdname : /data/share/DATA/ROMS_INPUTS/grd/roms_grd_fennel_15km_smooth_v2.nc

weight_file: /data/share/DATA/ROMS_INPUTS/wght/test_weight.nc
calc_weight: False

ncformat: NETCDF4 # NETCDF3_64BIT
force_write: True

flood_method_for_bry: edt #griddata / edt / linearND

ogcm_inputs:
  zeta:
    path: /data/share/DATA/RAW/00utc/
    varname: surf_el

  temp:
    path: /data/share/DATA/RAW/00utc/
    varname: water_temp

  salt:
    path: /data/share/DATA/RAW/00utc/
    varname: salinity

  u:
    path: /data/share/DATA/RAW/00utc/
    varname: water_u

  v:
    path: /data/share/DATA/RAW/00utc/
    varname: water_v

ogcm_var_name:
    longitude       : lon
    latitude        : lat
    depth           : depth
    time            : time

reference_var  : zeta
bry_start_date      : 2022-12-01 00:00:00 # 'YYYY-MM-DD HH:MM:SS'
bry_end_date        : 2023-01-02 00:00:00 # 'YYYY-MM-DD HH:MM:SS'

time_ref            : seconds since 2000-1-1 00:00:00

global_attrs: 
    title           : ROMS bry
    clm_file        : ROMS bry
    type            : ROMS bry

vertical:
    layer_n         : 36
    vtransform      : 2
    vstretching     : 4
    theta_s         : 6.5
    theta_b         : 1
    tcline          : 400




