###
#
# INFO
# This script is for HYCOM data
###

# === Define file names ===
#ininame : /mnt/c/Users/shjo9/Bridge/DATA/roms_ini.nc
bryname : /home/shjo/data/roms_inputs/bry/lte/NWP4_bry_subsampled.nc
grdname : /home/shjo/data/roms_inputs/grd/lte/NWP4_grd_3_10m_LP_subsampled.nc

weight_file: /home/shjo/data/roms_inputs/wght/wght_hycom_nwp4.nc
calc_weight: True

ncformat: NETCDF4 # NETCDF3_64BIT
force_write: True

bio_model_type: Fennel

flood_method_for_bry: edt #griddata / edt / linearND

ogcm_path: /home/shjo/data/raw/00utc/

ogcm_var_name:
    longitude       : lon
    latitude        : lat
    depth           : depth
    time            : time
    temperature     : water_temp
    salinity        : salinity
    u               : water_u
    v               : water_v
    zeta            : surf_el

bry_start_date      : 2022-12-31 00:00:00 # 'YYYY-MM-DD HH:MM:SS'
bry_end_date        : 2025-01-01 00:00:00 # 'YYYY-MM-DD HH:MM:SS'

time_ref            : seconds since 1980-1-1 00:00:00

global_attrs: 
    title           : ROMS bry
    clm_file        : ROMS bry
    type            : ROMS bry

vertical:
    layer_n         : 20
    vtransform      : 2
    vstretching     : 2
    theta_s         : 7.0
    theta_b         : 0.1
    tcline          : 200




