
case               : nifs01_clm
data_dir           : /home/shjo/applications/fennel_v1171/storage/nifs01_clm_8km/
data_prefix_header : nifs01_clm_avg
base_dir           : /home/shjo/tmp/

grdname            : /home/shjo/applications/isl_system_v250925/storage/data/NWP12_grd_NWP4_topo_modi.nc


vars: ["temp", "salt", "chlorophyll", "NO3","phytoplankton"]


var_names:
  time_candidates: ["ocean_time", "time", "t"]
  lat_candidates: ["lat", "latitude", "y", "eta", "eta_rho"]
  lon_candidates: ["lon", "longitude", "x", "xi", "xi_rho"]
  z_candidates: ["s_rho", "z", "depth", "lev", "layer"]
  ref_time: "seconds since 2000-1-1"


